name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  equatable: ^2.0.5
  logger: ^2.0.2+1
  get_it: ^7.6.4
  http: ^1.1.0
  intl_utils: ^2.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
flutter_intl:
  enabled: true